// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: bot_dialog_generator/v1/conversation.proto

package botdialoggeneratorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InboundMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tenant          string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Channel         string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageId       string                 `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,5,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*InboundMessage_Text
	//	*InboundMessage_Choice
	//	*InboundMessage_Location
	//	*InboundMessage_Media
	//	*InboundMessage_Event
	Body          isInboundMessage_Body `protobuf_oneof:"body"`
	Context       map[string]string     `protobuf:"bytes,11,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkspaceId   string                `protobuf:"bytes,12,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundMessage) Reset() {
	*x = InboundMessage{}
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundMessage) ProtoMessage() {}

func (x *InboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundMessage.ProtoReflect.Descriptor instead.
func (*InboundMessage) Descriptor() ([]byte, []int) {
	return file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *InboundMessage) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *InboundMessage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *InboundMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InboundMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *InboundMessage) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *InboundMessage) GetBody() isInboundMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *InboundMessage) GetText() *Text {
	if x != nil {
		if x, ok := x.Body.(*InboundMessage_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *InboundMessage) GetChoice() *Choice {
	if x != nil {
		if x, ok := x.Body.(*InboundMessage_Choice); ok {
			return x.Choice
		}
	}
	return nil
}

func (x *InboundMessage) GetLocation() *Location {
	if x != nil {
		if x, ok := x.Body.(*InboundMessage_Location); ok {
			return x.Location
		}
	}
	return nil
}

func (x *InboundMessage) GetMedia() *Media {
	if x != nil {
		if x, ok := x.Body.(*InboundMessage_Media); ok {
			return x.Media
		}
	}
	return nil
}

func (x *InboundMessage) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Body.(*InboundMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *InboundMessage) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *InboundMessage) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type isInboundMessage_Body interface {
	isInboundMessage_Body()
}

type InboundMessage_Text struct {
	Text *Text `protobuf:"bytes,6,opt,name=text,proto3,oneof"`
}

type InboundMessage_Choice struct {
	Choice *Choice `protobuf:"bytes,7,opt,name=choice,proto3,oneof"`
}

type InboundMessage_Location struct {
	Location *Location `protobuf:"bytes,8,opt,name=location,proto3,oneof"`
}

type InboundMessage_Media struct {
	Media *Media `protobuf:"bytes,9,opt,name=media,proto3,oneof"`
}

type InboundMessage_Event struct {
	Event *Event `protobuf:"bytes,10,opt,name=event,proto3,oneof"`
}

func (*InboundMessage_Text) isInboundMessage_Body() {}

func (*InboundMessage_Choice) isInboundMessage_Body() {}

func (*InboundMessage_Location) isInboundMessage_Body() {}

func (*InboundMessage_Media) isInboundMessage_Body() {}

func (*InboundMessage_Event) isInboundMessage_Body() {}

type OutboundBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReplyTo       string                 `protobuf:"bytes,4,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	Messages      []*OutMessage          `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,6,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundBatch) Reset() {
	*x = OutboundBatch{}
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundBatch) ProtoMessage() {}

func (x *OutboundBatch) ProtoReflect() protoreflect.Message {
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundBatch.ProtoReflect.Descriptor instead.
func (*OutboundBatch) Descriptor() ([]byte, []int) {
	return file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *OutboundBatch) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *OutboundBatch) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *OutboundBatch) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OutboundBatch) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *OutboundBatch) GetMessages() []*OutMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *OutboundBatch) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type OutMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*OutMessage_Text
	//	*OutMessage_Link
	//	*OutMessage_Media
	//	*OutMessage_Menu
	//	*OutMessage_QuickReplies
	//	*OutMessage_Location
	//	*OutMessage_Template
	Kind          isOutMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutMessage) Reset() {
	*x = OutMessage{}
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutMessage) ProtoMessage() {}

func (x *OutMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutMessage.ProtoReflect.Descriptor instead.
func (*OutMessage) Descriptor() ([]byte, []int) {
	return file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *OutMessage) GetKind() isOutMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *OutMessage) GetText() *Text {
	if x != nil {
		if x, ok := x.Kind.(*OutMessage_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *OutMessage) GetLink() *Link {
	if x != nil {
		if x, ok := x.Kind.(*OutMessage_Link); ok {
			return x.Link
		}
	}
	return nil
}

func (x *OutMessage) GetMedia() *Media {
	if x != nil {
		if x, ok := x.Kind.(*OutMessage_Media); ok {
			return x.Media
		}
	}
	return nil
}

func (x *OutMessage) GetMenu() *Menu {
	if x != nil {
		if x, ok := x.Kind.(*OutMessage_Menu); ok {
			return x.Menu
		}
	}
	return nil
}

func (x *OutMessage) GetQuickReplies() *QuickReplies {
	if x != nil {
		if x, ok := x.Kind.(*OutMessage_QuickReplies); ok {
			return x.QuickReplies
		}
	}
	return nil
}

func (x *OutMessage) GetLocation() *Location {
	if x != nil {
		if x, ok := x.Kind.(*OutMessage_Location); ok {
			return x.Location
		}
	}
	return nil
}

func (x *OutMessage) GetTemplate() *Template {
	if x != nil {
		if x, ok := x.Kind.(*OutMessage_Template); ok {
			return x.Template
		}
	}
	return nil
}

type isOutMessage_Kind interface {
	isOutMessage_Kind()
}

type OutMessage_Text struct {
	Text *Text `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type OutMessage_Link struct {
	Link *Link `protobuf:"bytes,2,opt,name=link,proto3,oneof"`
}

type OutMessage_Media struct {
	Media *Media `protobuf:"bytes,3,opt,name=media,proto3,oneof"`
}

type OutMessage_Menu struct {
	Menu *Menu `protobuf:"bytes,4,opt,name=menu,proto3,oneof"`
}

type OutMessage_QuickReplies struct {
	QuickReplies *QuickReplies `protobuf:"bytes,5,opt,name=quick_replies,json=quickReplies,proto3,oneof"`
}

type OutMessage_Location struct {
	Location *Location `protobuf:"bytes,6,opt,name=location,proto3,oneof"`
}

type OutMessage_Template struct {
	Template *Template `protobuf:"bytes,7,opt,name=template,proto3,oneof"`
}

func (*OutMessage_Text) isOutMessage_Kind() {}

func (*OutMessage_Link) isOutMessage_Kind() {}

func (*OutMessage_Media) isOutMessage_Kind() {}

func (*OutMessage_Menu) isOutMessage_Kind() {}

func (*OutMessage_QuickReplies) isOutMessage_Kind() {}

func (*OutMessage_Location) isOutMessage_Kind() {}

func (*OutMessage_Template) isOutMessage_Kind() {}

type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *Text) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Choice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choice.ProtoReflect.Descriptor instead.
func (*Choice) Descriptor() ([]byte, []int) {
	return file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP(), []int{4}
}

func (x *Choice) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP(), []int{6}
}

func (x *Media) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Media) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP(), []int{7}
}

func (x *Link) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Link) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP(), []int{8}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Template struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP(), []int{9}
}

func (x *Template) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Template) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type MenuOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuOption) Reset() {
	*x = MenuOption{}
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuOption) ProtoMessage() {}

func (x *MenuOption) ProtoReflect() protoreflect.Message {
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuOption.ProtoReflect.Descriptor instead.
func (*MenuOption) Descriptor() ([]byte, []int) {
	return file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP(), []int{10}
}

func (x *MenuOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Options       []*MenuOption          `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP(), []int{11}
}

func (x *Menu) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Menu) GetOptions() []*MenuOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type QuickReplies struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Options       []*MenuOption          `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuickReplies) Reset() {
	*x = QuickReplies{}
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuickReplies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickReplies) ProtoMessage() {}

func (x *QuickReplies) ProtoReflect() protoreflect.Message {
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickReplies.ProtoReflect.Descriptor instead.
func (*QuickReplies) Descriptor() ([]byte, []int) {
	return file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP(), []int{12}
}

func (x *QuickReplies) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *QuickReplies) GetOptions() []*MenuOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type BotDefinition struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Tenant      string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	AppId       string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Version     string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	EntryNodeId string                 `protobuf:"bytes,4,opt,name=entry_node_id,json=entryNodeId,proto3" json:"entry_node_id,omitempty"`
	Nodes       []*Node                `protobuf:"bytes,5,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges       []*Edge                `protobuf:"bytes,6,rep,name=edges,proto3" json:"edges,omitempty"`
	// The area that owns this bot. The engine refuses to run a definition against a
	// message or session from another workspace.
	WorkspaceId   string `protobuf:"bytes,7,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotDefinition) Reset() {
	*x = BotDefinition{}
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotDefinition) ProtoMessage() {}

func (x *BotDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotDefinition.ProtoReflect.Descriptor instead.
func (*BotDefinition) Descriptor() ([]byte, []int) {
	return file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP(), []int{13}
}

func (x *BotDefinition) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *BotDefinition) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *BotDefinition) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BotDefinition) GetEntryNodeId() string {
	if x != nil {
		return x.EntryNodeId
	}
	return ""
}

func (x *BotDefinition) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *BotDefinition) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *BotDefinition) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP(), []int{14}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Node) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Condition     string                 `protobuf:"bytes,3,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_bot_dialog_generator_v1_conversation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP(), []int{15}
}

func (x *Edge) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Edge) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Edge) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

var File_bot_dialog_generator_v1_conversation_proto protoreflect.FileDescriptor

const file_bot_dialog_generator_v1_conversation_proto_rawDesc = "" +
	"\n" +
	"*bot_dialog_generator/v1/conversation.proto\x12\x17bot_dialog_generator.v1\"\xfe\x04\n" +
	"\x0eInboundMessage\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tR\tmessageId\x12*\n" +
	"\x11timestamp_unix_ms\x18\x05 \x01(\x03R\x0ftimestampUnixMs\x123\n" +
	"\x04text\x18\x06 \x01(\v2\x1d.bot_dialog_generator.v1.TextH\x00R\x04text\x129\n" +
	"\x06choice\x18\a \x01(\v2\x1f.bot_dialog_generator.v1.ChoiceH\x00R\x06choice\x12?\n" +
	"\blocation\x18\b \x01(\v2!.bot_dialog_generator.v1.LocationH\x00R\blocation\x126\n" +
	"\x05media\x18\t \x01(\v2\x1e.bot_dialog_generator.v1.MediaH\x00R\x05media\x126\n" +
	"\x05event\x18\n" +
	" \x01(\v2\x1e.bot_dialog_generator.v1.EventH\x00R\x05event\x12N\n" +
	"\acontext\x18\v \x03(\v24.bot_dialog_generator.v1.InboundMessage.ContextEntryR\acontext\x12!\n" +
	"\fworkspace_id\x18\f \x01(\tR\vworkspaceId\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04body\"\xd9\x01\n" +
	"\rOutboundBatch\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x19\n" +
	"\breply_to\x18\x04 \x01(\tR\areplyTo\x12?\n" +
	"\bmessages\x18\x05 \x03(\v2#.bot_dialog_generator.v1.OutMessageR\bmessages\x12!\n" +
	"\fworkspace_id\x18\x06 \x01(\tR\vworkspaceId\"\xbb\x03\n" +
	"\n" +
	"OutMessage\x123\n" +
	"\x04text\x18\x01 \x01(\v2\x1d.bot_dialog_generator.v1.TextH\x00R\x04text\x123\n" +
	"\x04link\x18\x02 \x01(\v2\x1d.bot_dialog_generator.v1.LinkH\x00R\x04link\x126\n" +
	"\x05media\x18\x03 \x01(\v2\x1e.bot_dialog_generator.v1.MediaH\x00R\x05media\x123\n" +
	"\x04menu\x18\x04 \x01(\v2\x1d.bot_dialog_generator.v1.MenuH\x00R\x04menu\x12L\n" +
	"\rquick_replies\x18\x05 \x01(\v2%.bot_dialog_generator.v1.QuickRepliesH\x00R\fquickReplies\x12?\n" +
	"\blocation\x18\x06 \x01(\v2!.bot_dialog_generator.v1.LocationH\x00R\blocation\x12?\n" +
	"\btemplate\x18\a \x01(\v2!.bot_dialog_generator.v1.TemplateH\x00R\btemplateB\x06\n" +
	"\x04kind\"\x1c\n" +
	"\x04Text\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1e\n" +
	"\x06Choice\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1b\n" +
	"\x05Event\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"<\n" +
	"\x05Media\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\".\n" +
	"\x04Link\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"Z\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"\xac\x01\n" +
	"\bTemplate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12N\n" +
	"\tvariables\x18\x02 \x03(\v20.bot_dialog_generator.v1.Template.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\n" +
	"MenuOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"]\n" +
	"\x04Menu\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12=\n" +
	"\aoptions\x18\x02 \x03(\v2#.bot_dialog_generator.v1.MenuOptionR\aoptions\"e\n" +
	"\fQuickReplies\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12=\n" +
	"\aoptions\x18\x02 \x03(\v2#.bot_dialog_generator.v1.MenuOptionR\aoptions\"\x89\x02\n" +
	"\rBotDefinition\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\"\n" +
	"\rentry_node_id\x18\x04 \x01(\tR\ventryNodeId\x123\n" +
	"\x05nodes\x18\x05 \x03(\v2\x1d.bot_dialog_generator.v1.NodeR\x05nodes\x123\n" +
	"\x05edges\x18\x06 \x03(\v2\x1d.bot_dialog_generator.v1.EdgeR\x05edges\x12!\n" +
	"\fworkspace_id\x18\a \x01(\tR\vworkspaceId\"\xb8\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12M\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2-.bot_dialog_generator.v1.Node.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x04Edge\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1c\n" +
	"\tcondition\x18\x03 \x01(\tR\tconditionBdZbgithub.com/Nggerizo97/Dialog_Bot_Creation/bot_dialog_generator/libs/go/botdef/botdialoggeneratorv1b\x06proto3"

var (
	file_bot_dialog_generator_v1_conversation_proto_rawDescOnce sync.Once
	file_bot_dialog_generator_v1_conversation_proto_rawDescData []byte
)

func file_bot_dialog_generator_v1_conversation_proto_rawDescGZIP() []byte {
	file_bot_dialog_generator_v1_conversation_proto_rawDescOnce.Do(func() {
		file_bot_dialog_generator_v1_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bot_dialog_generator_v1_conversation_proto_rawDesc), len(file_bot_dialog_generator_v1_conversation_proto_rawDesc)))
	})
	return file_bot_dialog_generator_v1_conversation_proto_rawDescData
}

var file_bot_dialog_generator_v1_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_bot_dialog_generator_v1_conversation_proto_goTypes = []any{
	(*InboundMessage)(nil), // 0: bot_dialog_generator.v1.InboundMessage
	(*OutboundBatch)(nil),  // 1: bot_dialog_generator.v1.OutboundBatch
	(*OutMessage)(nil),     // 2: bot_dialog_generator.v1.OutMessage
	(*Text)(nil),           // 3: bot_dialog_generator.v1.Text
	(*Choice)(nil),         // 4: bot_dialog_generator.v1.Choice
	(*Event)(nil),          // 5: bot_dialog_generator.v1.Event
	(*Media)(nil),          // 6: bot_dialog_generator.v1.Media
	(*Link)(nil),           // 7: bot_dialog_generator.v1.Link
	(*Location)(nil),       // 8: bot_dialog_generator.v1.Location
	(*Template)(nil),       // 9: bot_dialog_generator.v1.Template
	(*MenuOption)(nil),     // 10: bot_dialog_generator.v1.MenuOption
	(*Menu)(nil),           // 11: bot_dialog_generator.v1.Menu
	(*QuickReplies)(nil),   // 12: bot_dialog_generator.v1.QuickReplies
	(*BotDefinition)(nil),  // 13: bot_dialog_generator.v1.BotDefinition
	(*Node)(nil),           // 14: bot_dialog_generator.v1.Node
	(*Edge)(nil),           // 15: bot_dialog_generator.v1.Edge
	nil,                    // 16: bot_dialog_generator.v1.InboundMessage.ContextEntry
	nil,                    // 17: bot_dialog_generator.v1.Template.VariablesEntry
	nil,                    // 18: bot_dialog_generator.v1.Node.PropertiesEntry
}
var file_bot_dialog_generator_v1_conversation_proto_depIdxs = []int32{
	3,  // 0: bot_dialog_generator.v1.InboundMessage.text:type_name -> bot_dialog_generator.v1.Text
	4,  // 1: bot_dialog_generator.v1.InboundMessage.choice:type_name -> bot_dialog_generator.v1.Choice
	8,  // 2: bot_dialog_generator.v1.InboundMessage.location:type_name -> bot_dialog_generator.v1.Location
	6,  // 3: bot_dialog_generator.v1.InboundMessage.media:type_name -> bot_dialog_generator.v1.Media
	5,  // 4: bot_dialog_generator.v1.InboundMessage.event:type_name -> bot_dialog_generator.v1.Event
	16, // 5: bot_dialog_generator.v1.InboundMessage.context:type_name -> bot_dialog_generator.v1.InboundMessage.ContextEntry
	2,  // 6: bot_dialog_generator.v1.OutboundBatch.messages:type_name -> bot_dialog_generator.v1.OutMessage
	3,  // 7: bot_dialog_generator.v1.OutMessage.text:type_name -> bot_dialog_generator.v1.Text
	7,  // 8: bot_dialog_generator.v1.OutMessage.link:type_name -> bot_dialog_generator.v1.Link
	6,  // 9: bot_dialog_generator.v1.OutMessage.media:type_name -> bot_dialog_generator.v1.Media
	11, // 10: bot_dialog_generator.v1.OutMessage.menu:type_name -> bot_dialog_generator.v1.Menu
	12, // 11: bot_dialog_generator.v1.OutMessage.quick_replies:type_name -> bot_dialog_generator.v1.QuickReplies
	8,  // 12: bot_dialog_generator.v1.OutMessage.location:type_name -> bot_dialog_generator.v1.Location
	9,  // 13: bot_dialog_generator.v1.OutMessage.template:type_name -> bot_dialog_generator.v1.Template
	17, // 14: bot_dialog_generator.v1.Template.variables:type_name -> bot_dialog_generator.v1.Template.VariablesEntry
	10, // 15: bot_dialog_generator.v1.Menu.options:type_name -> bot_dialog_generator.v1.MenuOption
	10, // 16: bot_dialog_generator.v1.QuickReplies.options:type_name -> bot_dialog_generator.v1.MenuOption
	14, // 17: bot_dialog_generator.v1.BotDefinition.nodes:type_name -> bot_dialog_generator.v1.Node
	15, // 18: bot_dialog_generator.v1.BotDefinition.edges:type_name -> bot_dialog_generator.v1.Edge
	18, // 19: bot_dialog_generator.v1.Node.properties:type_name -> bot_dialog_generator.v1.Node.PropertiesEntry
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_bot_dialog_generator_v1_conversation_proto_init() }
func file_bot_dialog_generator_v1_conversation_proto_init() {
	if File_bot_dialog_generator_v1_conversation_proto != nil {
		return
	}
	file_bot_dialog_generator_v1_conversation_proto_msgTypes[0].OneofWrappers = []any{
		(*InboundMessage_Text)(nil),
		(*InboundMessage_Choice)(nil),
		(*InboundMessage_Location)(nil),
		(*InboundMessage_Media)(nil),
		(*InboundMessage_Event)(nil),
	}
	file_bot_dialog_generator_v1_conversation_proto_msgTypes[2].OneofWrappers = []any{
		(*OutMessage_Text)(nil),
		(*OutMessage_Link)(nil),
		(*OutMessage_Media)(nil),
		(*OutMessage_Menu)(nil),
		(*OutMessage_QuickReplies)(nil),
		(*OutMessage_Location)(nil),
		(*OutMessage_Template)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bot_dialog_generator_v1_conversation_proto_rawDesc), len(file_bot_dialog_generator_v1_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bot_dialog_generator_v1_conversation_proto_goTypes,
		DependencyIndexes: file_bot_dialog_generator_v1_conversation_proto_depIdxs,
		MessageInfos:      file_bot_dialog_generator_v1_conversation_proto_msgTypes,
	}.Build()
	File_bot_dialog_generator_v1_conversation_proto = out.File
	file_bot_dialog_generator_v1_conversation_proto_goTypes = nil
	file_bot_dialog_generator_v1_conversation_proto_depIdxs = nil
}
